workflows:
  android-deploy-workflow:
    name: Andrio Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:  
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - google_credentials
    scripts:
      - name: Setup the keystore
        script: |
          echo $KeyStoreFile | base64 --decode > /tmp/senior-keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$Store_Password
          keyPassword=$Key_Password
          keyAlias=$keyStore_alias
          storeFile=/tmp/senior-keystore.jks
          EOF

      - name: Install dependencies
        script: flutter pub get  

     #The script below to run flutter test
      # - name: Run flutter test
      #   script: flutter test  

      - name: Build Andriod APK & ABB
        script: |
          flutter build apk --release
          flutter build appbundle

   
    
