workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      node: latest
      ruby: default

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Run tests
        script: |
          flutter test

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_CREDENTIALS
        track: internal
